# Generated by Django 4.0.6 on 2022-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=200)),
                ('standings', models.JSONField(null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('manager_id', models.IntegerField(null='FALSE')),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_team_name', models.CharField(max_length=201)),
            ],
        ),
    ]
