# Generated by Django 4.0.6 on 2022-08-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerGWHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(null='FALSE')),
                ('gw_points', models.IntegerField()),
                ('overall_rank', models.IntegerField()),
                ('gw_team_value', models.IntegerField()),
                ('gw_points_on_bench', models.IntegerField()),
                ('event_transfers', models.IntegerField()),
                ('event_transfers_cost', models.IntegerField()),
                ('automatic_subs', models.JSONField()),
                ('active_chip', models.CharField(max_length=200)),
                ('gw_captain_id', models.IntegerField()),
                ('gw_vice_captain_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='league_id',
            field=models.IntegerField(unique='True'),
        ),
        migrations.AlterField(
            model_name='leaguemanager',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.league'),
        ),
        migrations.AddConstraint(
            model_name='leaguemanager',
            constraint=models.UniqueConstraint(fields=('league_id', 'manager_id'), name='unique_league_manager'),
        ),
        migrations.AddField(
            model_name='managergwhistory',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.leaguemanager'),
        ),
    ]
